### ISSUE TITLE
Question: Is there a way to deploy only on a git tag?

### ISSUE THREAD

**Issue by variadico** [Azure/appservice-actions#4]
For example,  the YAML in th readme seems like it'll deploy on every push.

```
on: push

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - uses: actions/checkout@master
    
    # install dependencies, build, and test
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present
        
    # deploy web app using publish profile credentials
    - uses: azure/appservice-actions/webapp@master
      with: 
        app-name: node-rn
        publish-profile: ${{ secrets.azureWebAppPublishProfile }}
```

But, what if I only wanted to deploy every time I create a new git tag? Not every time I push.
