### ISSUE TITLE
Use env variable in image name

### ISSUE THREAD

**Issue by nicojs** [Azure/appservice-actions#6]
Hi 👋 

Is it possible to use an environment variable in the image name? Like this:

```
- uses: azure/appservice-actions/webapp-container@57f0636
      name: Deploy dashboard
      with:
        app-name: 'my-app'
        images: 'my-app/hello-world:${DOCKER_VERSION}'
```

I've set the `DOCKER_VERSION` in a previous step and I want to make sure that version is deployed here.

Thanks for any help. Awesome actions you have here
